// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BetterCommentsPlus
{
    internal sealed partial class Vsix
    {
        public const string Id = "Better Comments Plus.Ghost-Girls.646f2284-7979-4af0-a676-4f2d7693df8e";
        public const string Name = "Better Comments Plus";
        public const string Description = @"Better Comments is a Visual Studio extension that gives you the ability to customize the font and opacity of your comments independently of the editor's font settings. It also adds four additional comment classifications, each classification with its own customizable foreground.

This project was forked from omsharp/BetterComments.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Ghost-Girls";
        public const string Tags = "Better, Comments, Italic, Bold, Opacity, Font, Size, Categorize, Color, Colorize";
    }
}
